### ISSUE TITLE
NuGet plugin

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau#37]

**Comment by aarondandy** [comment]
I'm going take a shot at this, will let you know if I give up. Regarding design I was going to try to mirror Bau.MSBuild and use the "NuGet package" from NuGet for the implementation. I recently got rid of my ./.nuget/nuget.exe and want to keep it that way! Find me in JabbR if you already have thoughts on this plugin already (I'm sure you do).

**Comment by adamralph** [comment]
Great! Yes I think taking Bau.MSBuild as a starting point is a good idea.
Are you intending to use Nuget.Core? I guess that would work and could be a
bit neater than wrapping around Nuget.exe. I'm on the road until Monday but
I'll catch up with you on JabbR when I get back.

**Comment by aarondandy** [comment]
I dropped a note about it in Jabbr. I really want to use Nuget.Core but I don't think it can perform a restore operation. Because of that I am taking the command line as a non-dev dependency. For now I was just planning on searching the packages to find nuget.exe and then call into it. Perhaps later what could be done is to use reflection to load nuget.exe and call into the restore method. It's not too complex so if it makes sense to reference either one in the future I don't think it would be a big deal to branch and change that.

**Comment by aarondandy** [comment]
See also: https://github.com/aarondandy/bau-nuget

**Comment by aarondandy** [comment]
I finished the approach where I dynamically load the NuGet.exe assembly. Tests worked great, everything was fine, then I ran it through scriptcs. Turns out my powershell loads stuff as x64 while ncrunch is doing x86. So after I got it all "working" I later discovered it won't work at all... Now I am back to loading the CommandLine tool into ./packages and then just executing it for restore. What a bummer...

I think I may use NuGet.Core for pack and MAYBE push but use the command line for restore. Maybe having a way to allow users to elect to run it through NuGet.Core or NuGet.exe could be beneficial? Obviously I think only NuGet.exe would be supported for restore.

**Comment by aarondandy** [comment]
Using the command line approach I completed implementations for restore, pack, and push. It does not require `NuGet.exe` to be on the path or in `./.nuget` but instead relies on `scriptcs -install` to bring the `NuGet.CommandLine` package down as is the case with Bau itself. The Bau.NuGet package has a dependency on the CLI tool by removing the `developmentDependency="true"` from the plugin's packages.config file. I hope this will make it as easy as adding `Bau.NuGet` for everything to work.

I know this isn't as ideal as using NuGet.Core or reflecting into NuGet.exe ( [that was so terrible!](https://github.com/aarondandy/bau-nuget/blob/nuget_exe-reference/src/Bau.NuGet/NuGetCliReflectionWrapper.cs#L48)  ) but replicating and maintaining functionality for NuGet.Commands is pretty crazy: https://github.com/Haacked/NuGet/tree/master/src/CommandLine/Commands

The are very few tests but the coverage is decent. I will probably add unit tests later for some of the fluent methods and some other minor things.

https://github.com/aarondandy/bau-nuget/tree/dev

**Comment by adamralph** [comment]
@aarondandy thanks for taking this on! Ultimately I'd like the NuGet plug-in to be one of the 'core' plugins, living in the Bau organisation. I've created https://github.com/bau-build/bau-nuget and invited you to join the org with commit rights for that repo so you can push up your initial implementation whenever you feel ready.

**Comment by aarondandy** [comment]
That was my intent. I'll push the commits there when I get home.

**Comment by aarondandy** [comment]
The NuGet plugin has been published: [https://github.com/bau-build/bau-nuget](https://github.com/bau-build/bau-nuget)

I recommend that this issue be closed.

**Comment by adamralph** [comment]
Moved to https://github.com/bau-build/bau-nuget
